apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-second-app
  namespace: argocd   # keep this in argocd namespace
spec:
  project: default

  source:
    repoURL: https://github.com/Gilbert-Mutai/argocd-example-apps
    targetRevision: HEAD
    path: guestbook

  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
